### ISSUE TITLE
🐛 [bug] - ClusterTask not found

### ISSUE THREAD

**Issue by ckavili** [rht-labs/tech-exercise#302]
### 📝 Description
OpenShift Pipelines has removed the ClusterTask concept in favor of resolver. Currently, with the latest deployments, doing the Tekton steps is impossible. 

### 🚶 Steps to reproduce
Deploy the TL500 setup, and see that the Tekton pipeline fails with the `git-clone` task.

### 🧙‍♀️ Suggested solution
need to update theTekton pipeline to use `resolver` for the steps that are using ClusterTask

**Comment by ckavili** [comment]
the required update should be something like this 👇  I can get to probably next week but if anybody is willing to take it, please feel free to do that and let me know :)

```
  tasks:
    # Clone jukebox repository
    - name: fetch-app-repository
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines 
```
